# Generated by Django 3.2.15 on 2022-08-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('userhandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='servers',
            field=models.ManyToManyField(blank=True, related_name='servers', to='app.Server'),
        ),
    ]
