# Generated by Django 3.2.15 on 2022-08-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0002_auto_20220817_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
