# Generated by Django 3.2.7 on 2022-10-02 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0002_user_servers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friendlist',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
