# Generated by Django 3.2.15 on 2022-08-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0002_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
