# Generated by Django 3.2.15 on 2022-08-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0003_alter_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tag',
        ),
    ]
