# Generated by Django 3.2.15 on 2022-08-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
