# Generated by Django 3.2.7 on 2022-08-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profilepics/'),
        ),
    ]
