# Generated by Django 3.2.15 on 2022-08-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0005_remove_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blocked_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='servers',
        ),
    ]
