# Generated by Django 3.2.15 on 2022-08-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0006_auto_20220819_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
