# Generated by Django 3.2.15 on 2022-08-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0008_auto_20220819_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='profilepics'),
        ),
    ]
