# Generated by Django 3.2.15 on 2022-08-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
