# Generated by Django 3.2.7 on 2022-08-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0014_auto_20220819_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friend',
            new_name='friendlist',
        ),
    ]
