# Generated by Django 3.2.15 on 2022-08-22 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhandler', '0015_rename_friend_user_friendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_users',
            field=models.ManyToManyField(blank=True, related_name='pending', to=settings.AUTH_USER_MODEL),
        ),
    ]
