# Generated by Django 3.2.15 on 2022-08-17 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220817_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='updated',
        ),
        migrations.AddField(
            model_name='server',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='server',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='users',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='tag',
            field=models.IntegerField(default=0),
        ),
    ]
