# Generated by Django 3.2.15 on 2022-08-18 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('server', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='app.server')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='messages', to='app.Message'),
        ),
        migrations.AddField(
            model_name='server',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles', to='app.Role'),
        ),
        migrations.CreateModel(
            name='ServerMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.message')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.textchannel')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.server')),
            ],
            bases=('app.message',),
        ),
    ]
