# Generated by Django 3.2.15 on 2022-08-18 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220818_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceChannel',
            fields=[
                ('textchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.textchannel')),
            ],
            bases=('app.textchannel',),
        ),
        migrations.AddField(
            model_name='server',
            name='text_channels',
            field=models.ManyToManyField(blank=True, related_name='text_channels', to='app.TextChannel'),
        ),
        migrations.AddField(
            model_name='textchannel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='textchannel',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='textchannel',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='ChannelParticipants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textchannel',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.server'),
        ),
        migrations.AlterField(
            model_name='textchannel',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='server',
            name='voice_channels',
            field=models.ManyToManyField(blank=True, related_name='voice_channels', to='app.VoiceChannel'),
        ),
    ]
